# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobboleArticle',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('url_object_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='url标识')),
                ('front_image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='封面图url')),
                ('front_image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图存放路径')),
                ('praise_nums', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('fav_nums', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('comment_nums', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
            ],
        ),
    ]
