# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobbolearticle',
            table='tb_jobbole_article',
        ),
    ]
