# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181022_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuAnswer',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='知乎回答id')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('author_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='作者id')),
                ('content', models.TextField(verbose_name='内容')),
                ('praise_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('crawl_time', models.DateTimeField(verbose_name='爬取时间')),
                ('crawl_update_time', models.DateTimeField(blank=True, null=True, verbose_name='爬取更新时间')),
            ],
            options={
                'db_table': 'tb_zhihu_answer',
            },
        ),
        migrations.CreateModel(
            name='ZhihuQuestion',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='知乎提问id')),
                ('topics', models.CharField(blank=True, max_length=255, null=True, verbose_name='专题')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('title', models.CharField(max_length=255, verbose_name='标签')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('answer_num', models.PositiveIntegerField(default=0, verbose_name='回答数')),
                ('comments_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('watch_user_num', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('click_num', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('crawl_time', models.DateTimeField(verbose_name='爬取时间')),
                ('crawl_update_time', models.DateTimeField(blank=True, null=True, verbose_name='爬取更新时间')),
            ],
            options={
                'db_table': 'tb_zhihu_question',
            },
        ),
        migrations.AddField(
            model_name='zhihuanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ZhihuQuestion', verbose_name='知乎提问'),
        ),
    ]
