# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20181027_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='LagouJob',
            fields=[
                ('obj_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='url的md5')),
                ('url', models.URLField(max_length=255, verbose_name='url')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('salary_min', models.PositiveIntegerField(default=0, verbose_name='最低薪资')),
                ('salary_max', models.PositiveIntegerField(default=0, verbose_name='最高薪资')),
                ('job_city', models.CharField(blank=True, max_length=16, null=True, verbose_name='工作城市')),
                ('work_years_min', models.PositiveIntegerField(default=0, verbose_name='最低工作年限')),
                ('work_years_max', models.PositiveIntegerField(default=0, verbose_name='最高工作年限')),
                ('degree_need', models.CharField(blank=True, max_length=32, null=True, verbose_name='学历')),
                ('job_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='工作类型')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('job_advantage', models.CharField(blank=True, max_length=1024, null=True, verbose_name='职位诱惑')),
                ('job_desc', models.TextField(verbose_name='职位描述')),
                ('job_addr', models.CharField(blank=True, max_length=64, null=True, verbose_name='工作地点')),
                ('company_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='公司链接')),
                ('ccompany_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'tb_lagou_job',
            },
        ),
        migrations.AlterField(
            model_name='zhihuanswer',
            name='crawl_time',
            field=models.DateTimeField(verbose_name='爬虫派取时间'),
        ),
        migrations.AlterField(
            model_name='zhihuanswer',
            name='crawl_update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='爬虫更新时间'),
        ),
        migrations.AlterField(
            model_name='zhihuquestion',
            name='crawl_time',
            field=models.DateTimeField(verbose_name='爬虫派取时间'),
        ),
        migrations.AlterField(
            model_name='zhihuquestion',
            name='crawl_update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='爬虫更新时间'),
        ),
    ]
