# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20181101_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagoujob',
            old_name='ccompany_name',
            new_name='company_name',
        ),
    ]
