# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('intro', models.CharField(default='', max_length=255, verbose_name='简介')),
                ('image', models.ImageField(blank=True, default='default_author.jpg', max_length=200, null=True, upload_to='authors/', verbose_name='作者图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说作者',
                'verbose_name_plural': '小说作者',
                'db_table': 'tb_novel_author',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=32, unique=True, verbose_name='小说名称')),
                ('site_name', models.CharField(max_length=32, verbose_name='小说网站')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='小说链接')),
                ('image', models.ImageField(blank=True, default='default_novel.jpg', max_length=200, null=True, upload_to='novel/', verbose_name='小说图片')),
                ('intro', models.TextField(default='', verbose_name='小说简介')),
                ('read_nums', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('fav_nums', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('parser', models.CharField(default='biqugeParser', max_length=255, verbose_name='内容解析器')),
                ('enable', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否已完结')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Author', verbose_name='小说作者')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'tb_novel',
            },
        ),
        migrations.CreateModel(
            name='NovelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
                'db_table': 'tb_novel_category',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.NovelCategory', verbose_name='小说分类'),
        ),
    ]
