# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-02 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('obj_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='url的MD5')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='章节链接')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='章节顺序')),
                ('name', models.CharField(max_length=255, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Novel', verbose_name='小说')),
            ],
            options={
                'db_table': 'tb_chapter',
            },
        ),
    ]
